version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g @angular/cli
      - node --version

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ppd
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: no
